// <auto-generated />
namespace EntityFrameworkTest1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class criacao_coluna_Valido : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(criacao_coluna_Valido));
        
        string IMigrationMetadata.Id
        {
            get { return "201911060013584_criacao_coluna_Valido"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
